### PR TITLE
Support Laravel 6, 7 and 8

### PR DESCRIPTION
**Pull request by CasperLaiTW**
Support Laravel 6.* and 7.*

### CODE REVIEW

**Review by brumik — CHANGES_REQUESTED** [review]
Maybe you can update php version to >=7.2?

**Comment by brumik** [comment]
@jeroennoten Is it possible that this gets merged? `prerender.io` still shows this repo even that it is not working anymore. This PR could fix that.

**Comment by CasperLaiTW** [comment]
> Maybe you can update php version to >=7.2?

I can do this, but I'm not sure about backward compatible.

I think about changing php version to >= 7.2 for maintainer decide.

**Comment by StanBarrows** [comment]
@CasperLaiTW any chance to implement Laravel 8 support as well? Do you maintain a fork by yourself or interested in creating a new repo and reference it on prerender.io? I'm happy to help as long as 'valid' improvements get somehow merged.

**Comment by CasperLaiTW** [comment]
Hi @StanBarrows

I will push new commit for supporting laravel 8.

How about php version, if you want to upgrade version to >= 7.2, I can do it as well.

maybe new tag for laravel 6, 7 and 8, how do you think?

**Comment by CasperLaiTW** [comment]
if no one can merge the PR, I can fork and submit to new library on packagist.

but namespace should be different...

so people will need to update some code with new library.

@StanBarrows just let me know which one you prefer?

**Comment by StanBarrows** [comment]
Hi @CasperLaiTW 

Thanks for the latest commit. 

I would go for a new package as long as the initial creator of this package can not merge your PR (@jeroennoten any chance to merge this PR?) Makes it easier in the long run to maintain and use the package.

Do you need help with it?

Cheers
Stan

**Review by StanBarrows — APPROVED** [review]

**Comment by CasperLaiTW** [comment]
@StanBarrows sure, when you create new repo, you can invite me to maintain new repo 😃

**Comment by StanBarrows** [comment]
Would like to maintain < Laravel 8 ? Otherwise I would wait as long no on is requesting it.

image

**Comment by CasperLaiTW** [comment]
I think laravel 6+?

Laravel 6 is LTS version, support to Sep. 3, 2022

Do you think?

**Comment by StanBarrows** [comment]
Sure, I've sent you an invite.

**Comment by CasperLaiTW** [comment]
I got, I will join you soon.

**Comment by CasperLaiTW** [comment]
Moved to https://github.com/codebar-ag/Laravel-Prerender

**Pull request closed without merging**
