### PR TITLE
Allow user to choose between soft and real HTTP codes through the config file

### PR DESCRIPTION
**Pull request by ElGatoLoco**

### CODE REVIEW

**Comment by jeroennoten** [comment]
If you make sure that the Travis build passes, I'll merge this PR. Removing hhvm from .travis.yml is ok with me.

**Comment by thoop** [comment]
The middleware should not follow the redirect. The redirect should be returned to the crawler and the crawler will see the 301 and crawl the new URL later. Is there a reason you are changing that?

**Comment by ElGatoLoco** [comment]
@jeroennoten I removed hhvm from .travis.yml, so Travis build passes now.
@thoop Middleware isn't following the redirect, it's returning it to crawlers with a real 3xx status code. Without this option enabled, the crawler gets 200.

**Comment by jeroennoten** [comment]
Thanks!

**Comment by thoop** [comment]
Ah ok, great! I'd consider making that baseline so that it always returns the correct status code from Prerender instead of having to turn on the option.

**Pull request merged**
